// Mocks generated by Mockito 5.4.6 from annotations
// in segundo_cogni/test/features/sync/offline_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i28;
import 'package:segundo_cogni/core/constants/enums/progress_status.dart'
    as _i21;
import 'package:segundo_cogni/core/database/base_database_helper.dart' as _i2;
import 'package:segundo_cogni/features/evaluation/data/evaluation_local_datasource.dart'
    as _i12;
import 'package:segundo_cogni/features/evaluation/data/evaluation_remote_data_source.dart'
    as _i14;
import 'package:segundo_cogni/features/evaluation/domain/evaluation_entity.dart'
    as _i13;
import 'package:segundo_cogni/features/evaluator/data/evaluator_local_datasource.dart'
    as _i8;
import 'package:segundo_cogni/features/evaluator/data/evaluator_model.dart'
    as _i9;
import 'package:segundo_cogni/features/evaluator/data/evaluator_remote_data_source.dart'
    as _i10;
import 'package:segundo_cogni/features/evaluator/domain/evaluator_registration_data.dart'
    as _i11;
import 'package:segundo_cogni/features/module_instance/data/module_instance_local_datasource.dart'
    as _i19;
import 'package:segundo_cogni/features/module_instance/data/module_instance_model.dart'
    as _i20;
import 'package:segundo_cogni/features/module_instance/data/module_instance_remote_data_source.dart'
    as _i22;
import 'package:segundo_cogni/features/module_instance/domain/module_instance_entity.dart'
    as _i23;
import 'package:segundo_cogni/features/participant/data/participant_local_datasource.dart'
    as _i5;
import 'package:segundo_cogni/features/participant/data/participant_remote_data_source.dart'
    as _i7;
import 'package:segundo_cogni/features/participant/domain/participant_entity.dart'
    as _i6;
import 'package:segundo_cogni/features/recording_file/data/recording_file_local_datasource.dart'
    as _i24;
import 'package:segundo_cogni/features/recording_file/data/recording_file_model.dart'
    as _i25;
import 'package:segundo_cogni/features/recording_file/data/recording_file_remote_data_source.dart'
    as _i26;
import 'package:segundo_cogni/features/recording_file/domain/recording_file_entity.dart'
    as _i27;
import 'package:segundo_cogni/features/task/domain/task_entity.dart' as _i30;
import 'package:segundo_cogni/features/task/domain/task_repository.dart'
    as _i29;
import 'package:segundo_cogni/features/task_instance/data/task_instance_local_datasource.dart'
    as _i15;
import 'package:segundo_cogni/features/task_instance/data/task_instance_model.dart'
    as _i16;
import 'package:segundo_cogni/features/task_instance/data/task_instance_remote_data_source.dart'
    as _i17;
import 'package:segundo_cogni/features/task_instance/domain/task_instance_entity.dart'
    as _i18;
import 'package:sqflite_common/sqlite_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.BaseDatabaseHelper {
  _FakeBaseDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryCursor_3 extends _i1.SmartFake implements _i3.QueryCursor {
  _FakeQueryCursor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBatch_4 extends _i1.SmartFake implements _i3.Batch {
  _FakeBatch_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ParticipantLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockParticipantLocalDataSource extends _i1.Mock
    implements _i5.ParticipantLocalDataSource {
  MockParticipantLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseDatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeBaseDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.BaseDatabaseHelper);

  @override
  _i4.Future<int?> insertParticipant(
    _i3.DatabaseExecutor? txn,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertParticipant, [txn, data]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<List<_i6.ParticipantEntity>> getAllParticipants() =>
      (super.noSuchMethod(
            Invocation.method(#getAllParticipants, []),
            returnValue: _i4.Future<List<_i6.ParticipantEntity>>.value(
              <_i6.ParticipantEntity>[],
            ),
          )
          as _i4.Future<List<_i6.ParticipantEntity>>);

  @override
  _i4.Future<_i6.ParticipantEntity?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i6.ParticipantEntity?>.value(),
          )
          as _i4.Future<_i6.ParticipantEntity?>);

  @override
  _i4.Future<void> deleteParticipant(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteParticipant, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateParticipant(_i6.ParticipantEntity? participant) =>
      (super.noSuchMethod(
            Invocation.method(#updateParticipant, [participant]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.ParticipantEntity>> getParticipantsByEvaluatorId(
    int? evaluatorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getParticipantsByEvaluatorId, [evaluatorId]),
            returnValue: _i4.Future<List<_i6.ParticipantEntity>>.value(
              <_i6.ParticipantEntity>[],
            ),
          )
          as _i4.Future<List<_i6.ParticipantEntity>>);
}

/// A class which mocks [ParticipantRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockParticipantRemoteDataSource extends _i1.Mock
    implements _i7.ParticipantRemoteDataSource {
  MockParticipantRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> createParticipant(
    _i6.ParticipantEntity? participant,
    int? evaluatorId, {
    List<int>? selectedModuleIds,
    String? avatar,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createParticipant,
              [participant, evaluatorId],
              {#selectedModuleIds: selectedModuleIds, #avatar: avatar},
            ),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<bool> updateParticipant(
    int? id,
    _i6.ParticipantEntity? participant,
    int? evaluatorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateParticipant, [
              id,
              participant,
              evaluatorId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteParticipant(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteParticipant, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [EvaluatorLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvaluatorLocalDataSource extends _i1.Mock
    implements _i8.EvaluatorLocalDataSource {
  MockEvaluatorLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> insert(_i9.EvaluatorModel? evaluator) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [evaluator]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.EvaluatorModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i9.EvaluatorModel>>.value(
              <_i9.EvaluatorModel>[],
            ),
          )
          as _i4.Future<List<_i9.EvaluatorModel>>);

  @override
  _i4.Future<_i9.EvaluatorModel?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i9.EvaluatorModel?>.value(),
          )
          as _i4.Future<_i9.EvaluatorModel?>);

  @override
  _i4.Future<_i9.EvaluatorModel?> getFirstEvaluator() =>
      (super.noSuchMethod(
            Invocation.method(#getFirstEvaluator, []),
            returnValue: _i4.Future<_i9.EvaluatorModel?>.value(),
          )
          as _i4.Future<_i9.EvaluatorModel?>);

  @override
  _i4.Future<bool> hasAnyEvaluatorAdmin() =>
      (super.noSuchMethod(
            Invocation.method(#hasAnyEvaluatorAdmin, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> deleteById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> existsByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#existsByEmail, [email]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i9.EvaluatorModel?> getEvaluatorByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getEvaluatorByEmail, [email]),
            returnValue: _i4.Future<_i9.EvaluatorModel?>.value(),
          )
          as _i4.Future<_i9.EvaluatorModel?>);

  @override
  _i4.Future<_i9.EvaluatorModel?> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i4.Future<_i9.EvaluatorModel?>.value(),
          )
          as _i4.Future<_i9.EvaluatorModel?>);
}

/// A class which mocks [EvaluatorRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvaluatorRemoteDataSource extends _i1.Mock
    implements _i10.EvaluatorRemoteDataSource {
  MockEvaluatorRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> createEvaluator(_i11.EvaluatorRegistrationData? data) =>
      (super.noSuchMethod(
            Invocation.method(#createEvaluator, [data]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<bool> updateEvaluator(
    int? id,
    _i11.EvaluatorRegistrationData? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvaluator, [id, data]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteEvaluator(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvaluator, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [EvaluationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvaluationLocalDataSource extends _i1.Mock
    implements _i12.EvaluationLocalDataSource {
  MockEvaluationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseDatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeBaseDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.BaseDatabaseHelper);

  @override
  _i4.Future<int?> insertEvaluation(
    _i3.Transaction? txn,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertEvaluation, [txn, data]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<List<_i13.EvaluationEntity>> getAllEvaluations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEvaluations, []),
            returnValue: _i4.Future<List<_i13.EvaluationEntity>>.value(
              <_i13.EvaluationEntity>[],
            ),
          )
          as _i4.Future<List<_i13.EvaluationEntity>>);

  @override
  _i4.Future<_i13.EvaluationEntity?> getById(_i3.Database? db, int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [db, id]),
            returnValue: _i4.Future<_i13.EvaluationEntity?>.value(),
          )
          as _i4.Future<_i13.EvaluationEntity?>);
}

/// A class which mocks [EvaluationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvaluationRemoteDataSource extends _i1.Mock
    implements _i14.EvaluationRemoteDataSource {
  MockEvaluationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> createEvaluation(_i13.EvaluationEntity? evaluation) =>
      (super.noSuchMethod(
            Invocation.method(#createEvaluation, [evaluation]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<bool> updateEvaluationStatus(int? id, int? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvaluationStatus, [id, status]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [TaskInstanceLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskInstanceLocalDataSource extends _i1.Mock
    implements _i15.TaskInstanceLocalDataSource {
  MockTaskInstanceLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseDatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeBaseDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.BaseDatabaseHelper);

  @override
  _i4.Future<int?> create(_i16.TaskInstanceModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#create, [model]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<_i16.TaskInstanceModel?> getTaskInstance(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskInstance, [id]),
            returnValue: _i4.Future<_i16.TaskInstanceModel?>.value(),
          )
          as _i4.Future<_i16.TaskInstanceModel?>);

  @override
  _i4.Future<int> updateTaskInstance(_i16.TaskInstanceModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskInstance, [model]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteTaskInstance(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskInstance, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i16.TaskInstanceModel>> getAllTaskInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTaskInstances, []),
            returnValue: _i4.Future<List<_i16.TaskInstanceModel>>.value(
              <_i16.TaskInstanceModel>[],
            ),
          )
          as _i4.Future<List<_i16.TaskInstanceModel>>);

  @override
  _i4.Future<List<_i16.TaskInstanceModel>> getTaskInstancesForModuleInstance(
    int? moduleInstanceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskInstancesForModuleInstance, [
              moduleInstanceId,
            ]),
            returnValue: _i4.Future<List<_i16.TaskInstanceModel>>.value(
              <_i16.TaskInstanceModel>[],
            ),
          )
          as _i4.Future<List<_i16.TaskInstanceModel>>);

  @override
  _i4.Future<int?> getNumberOfTaskInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getNumberOfTaskInstances, []),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<_i16.TaskInstanceModel?> getFirstPendingTaskInstance() =>
      (super.noSuchMethod(
            Invocation.method(#getFirstPendingTaskInstance, []),
            returnValue: _i4.Future<_i16.TaskInstanceModel?>.value(),
          )
          as _i4.Future<_i16.TaskInstanceModel?>);

  @override
  _i4.Future<void> markAsCompleted(int? id, {String? duration}) =>
      (super.noSuchMethod(
            Invocation.method(#markAsCompleted, [id], {#duration: duration}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TaskInstanceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskInstanceRemoteDataSource extends _i1.Mock
    implements _i17.TaskInstanceRemoteDataSource {
  MockTaskInstanceRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> createTaskInstance(_i18.TaskInstanceEntity? instance) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskInstance, [instance]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<bool> markAsCompleted(int? id, String? duration) =>
      (super.noSuchMethod(
            Invocation.method(#markAsCompleted, [id, duration]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [ModuleInstanceLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockModuleInstanceLocalDataSource extends _i1.Mock
    implements _i19.ModuleInstanceLocalDataSource {
  MockModuleInstanceLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseDatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeBaseDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.BaseDatabaseHelper);

  @override
  _i4.Future<int?> insertModuleInstance(_i20.ModuleInstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#insertModuleInstance, [instance]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<_i20.ModuleInstanceModel?> getModuleInstanceById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getModuleInstanceById, [id]),
            returnValue: _i4.Future<_i20.ModuleInstanceModel?>.value(),
          )
          as _i4.Future<_i20.ModuleInstanceModel?>);

  @override
  _i4.Future<List<_i20.ModuleInstanceModel>> getAllModuleInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getAllModuleInstances, []),
            returnValue: _i4.Future<List<_i20.ModuleInstanceModel>>.value(
              <_i20.ModuleInstanceModel>[],
            ),
          )
          as _i4.Future<List<_i20.ModuleInstanceModel>>);

  @override
  _i4.Future<List<_i20.ModuleInstanceModel>> getModuleInstancesByEvaluationId(
    int? evaluationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getModuleInstancesByEvaluationId, [
              evaluationId,
            ]),
            returnValue: _i4.Future<List<_i20.ModuleInstanceModel>>.value(
              <_i20.ModuleInstanceModel>[],
            ),
          )
          as _i4.Future<List<_i20.ModuleInstanceModel>>);

  @override
  _i4.Future<int> updateModuleInstance(_i20.ModuleInstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#updateModuleInstance, [instance]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteModuleInstance(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteModuleInstance, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getCount() =>
      (super.noSuchMethod(
            Invocation.method(#getCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> setStatus(int? instanceId, _i21.ProgressStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#setStatus, [instanceId, status]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [ModuleInstanceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockModuleInstanceRemoteDataSource extends _i1.Mock
    implements _i22.ModuleInstanceRemoteDataSource {
  MockModuleInstanceRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> createModuleInstance(_i23.ModuleInstanceEntity? instance) =>
      (super.noSuchMethod(
            Invocation.method(#createModuleInstance, [instance]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<bool> updateModuleInstanceStatus(int? id, int? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateModuleInstanceStatus, [id, status]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [RecordingFileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordingFileLocalDataSource extends _i1.Mock
    implements _i24.RecordingFileLocalDataSource {
  MockRecordingFileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseDatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeBaseDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.BaseDatabaseHelper);

  @override
  _i4.Future<int?> insert(_i25.RecordingFileModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<_i25.RecordingFileModel?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i25.RecordingFileModel?>.value(),
          )
          as _i4.Future<_i25.RecordingFileModel?>);

  @override
  _i4.Future<_i25.RecordingFileModel?> getByTaskInstanceId(
    int? taskInstanceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByTaskInstanceId, [taskInstanceId]),
            returnValue: _i4.Future<_i25.RecordingFileModel?>.value(),
          )
          as _i4.Future<_i25.RecordingFileModel?>);

  @override
  _i4.Future<List<_i25.RecordingFileModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i25.RecordingFileModel>>.value(
              <_i25.RecordingFileModel>[],
            ),
          )
          as _i4.Future<List<_i25.RecordingFileModel>>);

  @override
  _i4.Future<int> update(_i25.RecordingFileModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [RecordingFileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordingFileRemoteDataSource extends _i1.Mock
    implements _i26.RecordingFileRemoteDataSource {
  MockRecordingFileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> createRecordingFile(_i27.RecordingFileEntity? recording) =>
      (super.noSuchMethod(
            Invocation.method(#createRecordingFile, [recording]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i3.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i28.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false)
          as bool);

  @override
  _i3.Database get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeDatabase_1(this, Invocation.getter(#database)),
          )
          as _i3.Database);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<T> transaction<T>(
    _i4.Future<T> Function(_i3.Transaction)? action, {
    bool? exclusive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action], {#exclusive: exclusive}),
            returnValue:
                _i28.ifNotNull(
                  _i28.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#exclusive: exclusive},
                    ),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_2<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#exclusive: exclusive},
                  ),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<T> readTransaction<T>(
    _i4.Future<T> Function(_i3.Transaction)? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readTransaction, [action]),
            returnValue:
                _i28.ifNotNull(
                  _i28.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#readTransaction, [action]),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_2<T>(
                  this,
                  Invocation.method(#readTransaction, [action]),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<T> devInvokeMethod<T>(String? method, [Object? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeMethod, [method, arguments]),
            returnValue:
                _i28.ifNotNull(
                  _i28.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeMethod, [method, arguments]),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_2<T>(
                  this,
                  Invocation.method(#devInvokeMethod, [method, arguments]),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<T> devInvokeSqlMethod<T>(
    String? method,
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#devInvokeSqlMethod, [method, sql, arguments]),
            returnValue:
                _i28.ifNotNull(
                  _i28.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#devInvokeSqlMethod, [
                      method,
                      sql,
                      arguments,
                    ]),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_2<T>(
                  this,
                  Invocation.method(#devInvokeSqlMethod, [
                    method,
                    sql,
                    arguments,
                  ]),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<void> execute(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sql, arguments]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> rawInsert(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawInsert, [sql, arguments]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insert(
    String? table,
    Map<String, Object?>? values, {
    String? nullColumnHack,
    _i3.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [table, values],
              {
                #nullColumnHack: nullColumnHack,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, Object?>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i4.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i4.Future<List<Map<String, Object?>>>);

  @override
  _i4.Future<List<Map<String, Object?>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i4.Future<List<Map<String, Object?>>>.value(
              <Map<String, Object?>>[],
            ),
          )
          as _i4.Future<List<Map<String, Object?>>>);

  @override
  _i4.Future<_i3.QueryCursor> rawQueryCursor(
    String? sql,
    List<Object?>? arguments, {
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rawQueryCursor,
              [sql, arguments],
              {#bufferSize: bufferSize},
            ),
            returnValue: _i4.Future<_i3.QueryCursor>.value(
              _FakeQueryCursor_3(
                this,
                Invocation.method(
                  #rawQueryCursor,
                  [sql, arguments],
                  {#bufferSize: bufferSize},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.QueryCursor>);

  @override
  _i4.Future<_i3.QueryCursor> queryCursor(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
    int? bufferSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryCursor,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
                #bufferSize: bufferSize,
              },
            ),
            returnValue: _i4.Future<_i3.QueryCursor>.value(
              _FakeQueryCursor_3(
                this,
                Invocation.method(
                  #queryCursor,
                  [table],
                  {
                    #distinct: distinct,
                    #columns: columns,
                    #where: where,
                    #whereArgs: whereArgs,
                    #groupBy: groupBy,
                    #having: having,
                    #orderBy: orderBy,
                    #limit: limit,
                    #offset: offset,
                    #bufferSize: bufferSize,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i3.QueryCursor>);

  @override
  _i4.Future<int> rawUpdate(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> update(
    String? table,
    Map<String, Object?>? values, {
    String? where,
    List<Object?>? whereArgs,
    _i3.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [table, values],
              {
                #where: where,
                #whereArgs: whereArgs,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> rawDelete(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [table],
              {#where: where, #whereArgs: whereArgs},
            ),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i3.Batch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeBatch_4(this, Invocation.method(#batch, [])),
          )
          as _i3.Batch);
}

/// A class which mocks [BaseDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseDatabaseHelper extends _i1.Mock
    implements _i2.BaseDatabaseHelper {
  MockBaseDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get dbName =>
      (super.noSuchMethod(
            Invocation.getter(#dbName),
            returnValue: _i28.dummyValue<String>(
              this,
              Invocation.getter(#dbName),
            ),
          )
          as String);

  @override
  int get dbVersion =>
      (super.noSuchMethod(Invocation.getter(#dbVersion), returnValue: 0)
          as int);

  @override
  _i4.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i3.Database>);

  @override
  _i4.Future<void> onCreate(_i3.Database? db, int? version) =>
      (super.noSuchMethod(
            Invocation.method(#onCreate, [db, version]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> onUpgrade(
    _i3.Database? db,
    int? oldVersion,
    int? newVersion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onUpgrade, [db, oldVersion, newVersion]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.Database> initDb() =>
      (super.noSuchMethod(
            Invocation.method(#initDb, []),
            returnValue: _i4.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.method(#initDb, [])),
            ),
          )
          as _i4.Future<_i3.Database>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDb() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDb, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setDbInstance(_i3.Database? db) => super.noSuchMethod(
    Invocation.method(#setDbInstance, [db]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i29.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> insertTask(_i30.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#insertTask, [task]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<_i30.TaskEntity?> getTaskById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i4.Future<_i30.TaskEntity?>.value(),
          )
          as _i4.Future<_i30.TaskEntity?>);

  @override
  _i4.Future<List<_i30.TaskEntity>> getAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTasks, []),
            returnValue: _i4.Future<List<_i30.TaskEntity>>.value(
              <_i30.TaskEntity>[],
            ),
          )
          as _i4.Future<List<_i30.TaskEntity>>);

  @override
  _i4.Future<List<_i30.TaskEntity>> getTasksByModuleId(int? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByModuleId, [moduleId]),
            returnValue: _i4.Future<List<_i30.TaskEntity>>.value(
              <_i30.TaskEntity>[],
            ),
          )
          as _i4.Future<List<_i30.TaskEntity>>);

  @override
  _i4.Future<int> updateTask(_i30.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
